- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
      # Import variables files
    - name: import vpc variable files
      include_vars: vars/vpc_setup
     
      #create vpc range
    - name: create vprofile vpc
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{ state }}"
      register: vpcout
