- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    #import vpc out variable file
    - name: import vpc variable files
      include_vars: vars/vpc_output_vars

    #
    - name: Provision a set of instances
      ec2:
         key_name: my_key
         group: test
         instance_type: t2.micro
         image: "{{ ami_id }}"
         wait: true
         exact_count: 5
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2out