- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    #import vpc out variable file
    - name: import vpc out variable files
      include_vars: vars/vpc_output_vars
    
    #import vpro-stac-setup variable file
    - name: import vpro stack variable file
      include_vars: vars/vpro_stack_setup

    # we need a key to login to our instances
    - name: create ec2 key
      ec2_key:
        name: vprofile_stack_keypair
        region: "{{ region }}"
      register: keyout
    
    # and store taht key
    - name: store login key
      copy:
        content: "{{ keyout.key.private_key }}"
        destination: ./vprofile_stack_keypair.pem
        mode: 0600
      when: keyout.changed

    #create load balancer security group
    - name: load balancer security group
      ec2_group:
        name: vprofile_ELB_SG
        description: allow all ports from everywhere and and all port within sg
        vpc_id: "{{ vpc_id }}"
        #profile: "{{ aws_profile }}"
        region: "{{ region }}"
        rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port 80
      register: vprofile_ELB_SGout