- name: Set host to ip mapping in /etc/hosts file of all the instances in the stack
  hosts: all
  tasks:
    - name: Import VPC setup Variable
      include_vars: group_vars/hostsip

    - name: Update hosts file for all the hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {{web01-ip}} web01
          {{app01-ip}} app01
          {{rmq01-ip}} rmq01
          {{mc01-ip}} mc01
          {{db01-ip}} db01